### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] add index.html file and create HTML skeleton
- [x] add div class = "container" to body
- [x] add div class = "car" and car image inside div 
- [x] add styles.css file and link element in HTML document 
- [x] style content
- [x] fix errors and remove unnecessary styling
