### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add main.js file and script tag 
- [x] addEventListener and listen for keydown events
- [x] make data model that includes which way the car is facing
